### ISSUE TITLE
Javascript is bad

### ISSUE THREAD

**Issue by PKD667** [TheHolyTachanka/VsCopium#1]

**Comment by TheHolyTachanka** [comment]
Just like my skill, gottem em

**Comment by PKD667** [comment]
js appart , i have high hopes in this project

**Comment by TheHolyTachanka** [comment]
> js appart , i have high hopes in this project

As i said in discord im terrible with JS so i want to write as less as i can so there wont be much JS in the end but thx hopefully it can be used as a text editor soon if anyone wants to contribute they are welcome
